# Generated by Django 5.2.4 on 2025-07-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_customuser_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='學號'),
        ),
    ]
