# Generated by Django 5.2.4 on 2025-07-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_customuser_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='points',
            field=models.PositiveIntegerField(default=10, help_text='每題配分 (0-100)', verbose_name='配分'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='score',
            field=models.FloatField(default=0.0, help_text='題目得分 (0-100)', verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='學號'),
        ),
    ]
