# Generated by Django 5.2.4 on 2025-07-19 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_examquestion_points_interactionlog_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='correct_answer',
            field=models.TextField(blank=True, null=True, verbose_name='正確答案'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止時間'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='選項（選擇題專用）'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='公佈時間'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', '選擇題'), ('essay', '問答題'), ('tf', '是非題')], default='essay', max_length=10, verbose_name='題型'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='學號'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='points',
            field=models.PositiveIntegerField(default=10, help_text='每題配分 (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='配分'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='score',
            field=models.FloatField(default=0.0, help_text='題目得分 (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='得分'),
        ),
    ]
