# Generated by Django 5.2.4 on 2025-07-20 03:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_examquestion_correct_answer_examquestion_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='interactionlog',
            name='attempt_count',
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='截止時間'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='題目圖片'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='max_attempts',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大嘗試次數'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='選項列表'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='points',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='配分'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='發佈時間'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('tf', 'True/False'), ('sa', 'Short Answer')], default='sa', max_length=10, verbose_name='題型'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='exam_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.examquestion', verbose_name='相關題目'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='question',
            field=models.TextField(verbose_name='問題'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='response',
            field=models.TextField(verbose_name='回覆'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='score',
            field=models.IntegerField(default=0, verbose_name='得分'),
        ),
    ]
