# Generated by Django 5.2.4 on 2025-07-20 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_remove_examquestion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='max_attempts',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大嘗試次數'),
        ),
    ]
