# Generated by Django 5.2.4 on 2025-07-20 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_examquestion_max_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='考卷名稱')),
                ('total_points', models.IntegerField(default=0, verbose_name='總分')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='發佈時間')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='截止時間')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='exam_papers/', verbose_name='考卷 PDF')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('questions', models.ManyToManyField(to='room.examquestion', verbose_name='包含題目')),
            ],
            options={
                'verbose_name': '考卷',
                'verbose_name_plural': '考卷',
            },
        ),
    ]
