# Generated by Django 5.2.4 on 2025-07-20 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_exampaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='max_attempts',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大嘗試次數'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('sc', 'Single Choice'), ('mcq', 'Multiple Choice'), ('tf', 'True/False'), ('sa', 'Short Answer')], default='sa', max_length=10, verbose_name='題型'),
        ),
    ]
