# Generated by Django 5.2.4 on 2025-07-21 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_alter_examquestion_max_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='考試描述'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='duration_minutes',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='考試持續時間（分鐘）'),
        ),
    ]
