# Generated by Django 5.2.4 on 2025-07-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_exampaper_description_exampaper_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='start_time',
        ),
    ]
