# Generated by Django 5.2.4 on 2025-07-22 11:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_remove_examquestion_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='總分')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交時間')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.exampaper', verbose_name='考卷')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL, to_field='student_id', verbose_name='學生')),
            ],
            options={
                'verbose_name': '考試紀錄',
                'verbose_name_plural': '考試紀錄',
                'unique_together': {('student', 'exam_paper')},
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(blank=True, null=True, verbose_name='學生答案')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='得分')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正確')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='回答時間')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.examquestion', verbose_name='題目')),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='room.examrecord', verbose_name='考試紀錄')),
            ],
            options={
                'verbose_name': '題目答案',
                'verbose_name_plural': '題目答案',
                'unique_together': {('exam_record', 'exam_question')},
            },
        ),
    ]
