# Generated by Django 5.2.4 on 2025-07-22 11:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_examrecord_examanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examanswer',
            options={'verbose_name': '答題紀錄', 'verbose_name_plural': '答題紀錄'},
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='exam_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_details', to='room.examrecord', verbose_name='考試紀錄'),
        ),
        migrations.CreateModel(
            name='StudentExamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='總分')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='等級')),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.exampaper', verbose_name='考卷')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_history', to=settings.AUTH_USER_MODEL, to_field='student_id', verbose_name='學生')),
            ],
            options={
                'verbose_name': '考試歷史紀錄',
                'verbose_name_plural': '考試歷史紀錄',
                'unique_together': {('student', 'exam_paper')},
            },
        ),
    ]
