# Generated by Django 5.2.4 on 2025-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_alter_examanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='correct_answer',
            field=models.BooleanField(default=False, verbose_name='正確答案'),
        ),
    ]
