# Generated by Django 5.2.4 on 2025-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_alter_examquestion_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='correct_option_indices',
            field=models.TextField(blank=True, null=True, verbose_name='正確選項索引'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否正確'),
        ),
    ]
