# Generated by Django 5.2.4 on 2025-08-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0015_remove_examquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='ai_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 表示無限制', verbose_name='AI 問答次數限制'),
        ),
    ]
