# Generated by Django 5.2.4 on 2025-08-18 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_examquestion_ai_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlog',
            name='exam_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.exampaper', verbose_name='相關考卷'),
        ),
    ]
