# Generated by Django 5.2.4 on 2025-08-27 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_interactionlog_exam_paper'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentexamhistory',
            name='exam_paper_name',
            field=models.CharField(default='', max_length=200, verbose_name='考卷名稱'),
        ),
        migrations.AddField(
            model_name='studentexamhistory',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.examquestion', verbose_name='題目'),
        ),
        migrations.AddField(
            model_name='studentexamhistory',
            name='question_content',
            field=models.TextField(default='', verbose_name='題目內容'),
        ),
        migrations.AddField(
            model_name='studentexamhistory',
            name='student_answer',
            field=models.TextField(blank=True, null=True, verbose_name='學生答案'),
        ),
        migrations.AddField(
            model_name='studentexamhistory',
            name='student_name',
            field=models.CharField(default='', max_length=150, verbose_name='學生名稱'),
        ),
        migrations.AlterUniqueTogether(
            name='studentexamhistory',
            unique_together={('student', 'exam_paper', 'question')},
        ),
    ]
