# Generated by Django 5.2.4 on 2025-08-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_alter_studentexamhistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamhistory',
            unique_together={('student', 'exam_paper', 'question_content')},
        ),
        migrations.RemoveField(
            model_name='studentexamhistory',
            name='question',
        ),
    ]
